import React, { useState, useEffect } from 'react';

export default function Stats() {
  const [loading, setLoading] = useState(true);
  const [stats, setStats] = useState({
    totalLeads: 0,
    totalBookings: 0,
    conversionRate: '0%',
    revenueRecovered: '$0'
  });

  // 🚨 Wahi same test Vendor ID:
  const VENDOR_ID = "feabc10c-a78b-4288-bb54-50cd78e0145d";
  const BASE_URL = "http://localhost:5000/api/v1/dashboard";

  useEffect(() => {
    const fetchStats = async () => {
      try {
        setLoading(true);
        const response = await fetch(`${BASE_URL}/stats?vendorId=${VENDOR_ID}`);
        const data = await response.json();

        if (data.success) {
          setStats(data.stats);
        }
      } catch (error) {
        console.error("❌ Error fetching stats:", error);
      } finally {
        setLoading(false);
      }
    };

    fetchStats();
  }, []);

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-[400px]">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
      </div>
    );
  }

  return (
    <div className="p-6 space-y-6 animate-fadeIn">
      {/* Page Header */}
      <div>
        <h1 className="text-2xl font-bold text-slate-900 tracking-tight">Performance Overview</h1>
        <p className="text-sm text-slate-500 mt-1">Real-time metrics calculated from your AI voice and chat interactions.</p>
      </div>

      {/* 4 Core Stats Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        
        {/* Card 1: Total Leads */}
        <div className="bg-white border border-slate-200 rounded-xl p-6 shadow-sm hover:shadow-md transition-shadow">
          <div className="flex items-center justify-between">
            <span className="text-xs font-semibold text-slate-400 uppercase tracking-wider">Total Leads</span>
            <span className="p-2 bg-slate-100 text-slate-600 rounded-lg text-xs font-bold">📞 Voice & 💬 Chat</span>
          </div>
          <div className="mt-4 flex items-baseline justify-between">
            <div className="text-3xl font-extrabold text-slate-900">{stats.totalLeads}</div>
          </div>
          <p className="text-xs text-slate-500 mt-2">Total customer conversations</p>
        </div>

        {/* Card 2: Booked Appointments */}
        <div className="bg-white border border-slate-200 rounded-xl p-6 shadow-sm hover:shadow-md transition-shadow">
          <div className="flex items-center justify-between">
            <span className="text-xs font-semibold text-slate-400 uppercase tracking-wider">Jobs Booked</span>
            <span className="p-2 bg-blue-50 text-blue-600 rounded-lg text-xs font-bold">📅 Calendar</span>
          </div>
          <div className="mt-4 flex items-baseline justify-between">
            <div className="text-3xl font-extrabold text-slate-900">{stats.totalBookings}</div>
          </div>
          <p className="text-xs text-slate-500 mt-2">Confirmed dispatch appointments</p>
        </div>

        {/* Card 3: Conversion Rate */}
        <div className="bg-white border border-slate-200 rounded-xl p-6 shadow-sm hover:shadow-md transition-shadow">
          <div className="flex items-center justify-between">
            <span className="text-xs font-semibold text-slate-400 uppercase tracking-wider">AI Close Rate</span>
            <span className="p-2 bg-emerald-50 text-emerald-600 rounded-lg text-xs font-bold">⚡ Efficiency</span>
          </div>
          <div className="mt-4 flex items-baseline justify-between">
            <div className="text-3xl font-extrabold text-emerald-600">{stats.conversionRate}</div>
          </div>
          <p className="text-xs text-slate-500 mt-2">Leads turned into paying jobs</p>
        </div>

        {/* Card 4: Est. Revenue Recovered ( 🔥 The King Metric) */}
        <div className="bg-gradient-to-br from-slate-900 to-slate-800 text-white rounded-xl p-6 shadow-lg relative overflow-hidden">
          <div className="flex items-center justify-between relative z-10">
            <span className="text-xs font-semibold text-slate-400 uppercase tracking-wider">Est. Revenue Recovered</span>
            <span className="p-2 bg-blue-500/20 text-blue-400 rounded-lg text-xs font-bold">$350/job avg</span>
          </div>
          <div className="mt-4 flex items-baseline justify-between relative z-10">
            <div className="text-3xl font-extrabold text-white tracking-tight">{stats.revenueRecovered}</div>
          </div>
          <p className="text-xs text-slate-400 mt-2 relative z-10">Generated by ClimateAI automating bookings</p>
        </div>

      </div>
    </div>
  );
}